name: Fetch assets (backgrounds & music)
on:
  schedule:
    - cron: "0 5 * * *"   # 05:00 UTC ежедневно (08:00 Киев, лето)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure folders
        run: |
          mkdir -p assets/backgrounds assets/music assets/fonts data
      - name: Install deps
        run: |
          python3 -V
          pip3 install requests
      - name: Fetch backgrounds
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          TARGET_BG_COUNT: "120"
        run: |
          python3 scripts/fetch_assets.py
      - name: Fetch music
        env:
          TARGET_MUSIC_COUNT: "30"
        run: |
          python3 scripts/fetch_music.py
      - name: Commit assets (optional)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || (git commit -m "Update assets" && git push)
