name: AutoPost

on:
  schedule:
    - cron: "0 7,16 * * *"  # 10:00 и 19:00 Киевское время UTC+3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main.py
      env:
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      run: python main.py
